package io.github.howtis.pythonembed.examples;

import io.github.howtis.pythonembed.PythonEmbed;
import io.github.howtis.pythonembed.PythonValue;

/**
 * Demonstrates PythonEmbed with the Maven plugin.
 *
 * <p>Build with {@code mvn compile python-embed:setup exec:java}
 * or just {@code mvn compile exec:java} (the setup goal runs on generate-resources by default).
 *
 * <p>The Maven plugin ({@code python-embed:setup}) handles Python installation,
 * venv creation, and package installation at build time — just like the Gradle plugin.
 */
public class MavenExample {

    public static void main(String[] args) throws Exception {
        System.out.println("=== PythonEmbed Maven Example ===");
        System.out.println();

        // PythonEmbed auto-discovers the venv from python-embed.properties
        // generated by the Maven plugin.
        try (PythonEmbed py = PythonEmbed.create()) {
            // Run Python code
            py.exec("x = 42");
            int x = py.eval("x * 2").asInt();
            System.out.println("42 * 2 = " + x);

            // Work with numpy (installed by the Maven plugin)
            py.exec("import numpy as np");
            PythonValue result = py.eval("[int(x) for x in np.linspace(0, 10, 2)]");
            System.out.println("numpy.linspace(0, 10, 2): " + result.asList());

            // Call a Python function
            py.exec("""
                    def hello(name):
                        return f"Hello, {name} from Python!"
                    """);
            String msg = py.eval("hello('Maven')").asString();
            System.out.println(msg);
        }

        System.out.println();
        System.out.println("Done!");
    }
}
